version: "3"
services:
  tsapi:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: yarn dev
    ports:
      - "4000:4000"
    links:
      - mongodb
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

volumes:
  node_modules:
