version: "3"
services:
  # tsapi:
  #   build: .
  #   volumes:
  #     - ./:/app
  #     - node_modules:/app/node_modules
  #   command: yarn dev
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - mongodb
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=4000

  tsapibdd:
    build: .
    volumes:
      - ./:/app
      - node_modules_bdd:/app/node_modules
    command: yarn dev
    ports:
      - "4001:4001"
    links:
      - mongodb
    environment:
      - NODE_ENV=testing
      - PORT=4001
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

volumes:
  # node_modules:
  node_modules_bdd:
